Final group capstone - Yacht Reservation App
akos29/book_appointment_front pull request #14
Opened 2023-09-06 17:54 UTC by akos29

Final group capstone - Yacht Reservation App
--
Hello 👋,

In this PR, we excited to introduce our yacht booking app. We've put in a lot of effort to bring this project to life. Here are the key highlights of what we've achieved:

- Repository Setup:

  - [ ] Created separate repositories for the front-end and back-end.
  - [ ] Organized code structure for scalability and maintainability.
  - [ ] Dependencies Installed
  - [ ]  Installed all necessary dependencies for both the front-end and back-end, ensuring a smooth development process.
  - [ ] Use `git flow` , `linters` and `rubocop`

- API Endpoints:
  - [ ] Developed robust API endpoints in the back-end to support yacht booking functionalities.
  - [ ]   Defined routes, controllers, and models for seamless data management.
- Front-End Pages:
  - [ ]  Crafted user-friendly front-end pages for the yacht booking app.
  - [ ] Employed responsive design principles for optimal user experience.
  - [ ] Styled pages using Bootstrap and custom CSS for an appealing look.
- API Integration
  - [ ]  Established seamless communication between the front-end and back-end through API requests.
  - [ ] - Dynamically fetched and displayed content based on API responses.
- Testing:
  - [ ]  tested both the front-end and back-end to ensure the reliability and functionality of our app.
  - [ ] Utilized appropriate testing frameworks for efficient testing workflows.
API Documentation:
- [ ] Created comprehensive API documentation using Swagger, making it easier for developers to understand and use our APIs.

Link to the Back-End's [PR:](https://github.com/akos29/book_appointment/pull/32)

We look forward to your review and feedback on our yacht booking app. Thank you for your time and support! 😊

2023-09-06 19:50 UTC, Meltrust requested changes
Hi @akos29,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!










#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-09-06 19:50 UTC, Meltrust commented on README.md
> +  <h3><b>YoYachts</b></h3>
- [ ] This is the default test that comes with React, kindly remove it:

![image](https://github.com/akos29/book_appointment_front/assets/57421823/eeddda68-bda3-4f09-9459-6ba2d9c8de4d)

2023-09-06 19:50 UTC, Meltrust commented on src/App.js
>  function App() {
- [ ]  Please, kindly refactor this main App component to ES6 arrow function, so your code complies with the latest standards.

Refactoring is easy:

```javascript
const App = () => {
  // ...
}
```

## Explanation

The `function` keyword has been soft deprecated in almost all the software industry in favor of ES6 arrow functions. This means, almost nobody uses it anymore, so much that it's considered a non-best practice.

That way, your code will meet the latest standards. 💪

2023-09-06 19:50 UTC, Meltrust commented on src/App.js
>  function App() {
- [ ] Since I wasn't able to run the backend, I can't test the frontend functionality.  This will be taken a look in the next review.

2023-09-07 18:26 UTC, mcrd25 requested changes
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Thanks for making changes requested by the previous reviewer

 ## Required Changes ♻️
_Check the comments under the review._
- Don't forget that the application needs to look exactly like design with exception of photos, titles and descriptions. A prime example is the yachts page. I see no carousel functionality like the original design, this is a big deviation. While I love the look of your app, what happens when even more yacths are added?

## Optional suggestions
- The reserve modal close option is not immediately visible to user, consider making it more visible with font thickness and size(maybe use X instead) or adding the close icon on the form modal itself. 
![image](https://github.com/akos29/book_appointment_front/assets/31193823/e0ac3739-d87a-42bf-9476-4e8ea186a4fc)
*  I am not seeing tests for your Front-End code - this is something we expect to be implemented for the final evaluation. Here are some resources you can use:
   *  https://reactjs.org/docs/testing.html
   * https://jestjs.io/docs/tutorial-react
   * https://www.freecodecamp.org/news/testing-react-hooks/

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_Also, you do not have to implement all requested changes, as this is up to you in the end, but I strongly recommend you implement them._

2023-09-07 18:26 UTC, mcrd25 commented on src/components/reservation/ReservationForm.jsx
> +              </select>
person should really know what they are reserving, image should be visible so they can be sure it's the right yacht they are reserve. [OPTIONAL]

2023-09-07 18:26 UTC, mcrd25 commented on src/components/DeleteYacht.jsx
> +};
Consider limiting 'DELETE YACHT' functionality to yachts the person created themselves or admin user.

2023-09-07 18:26 UTC, mcrd25 commented on src/components/AddYacht.jsx
> +              value={price}
Should I really be able to set price at 0? Maybe you cna limit this on back-end or front-end side [OPTIONAL]

2023-09-07 18:26 UTC, mcrd25 commented on src/components/reservation/ReservationForm.jsx
> +          </label>
[OPTIONAL] Consider valdiating city chosen. I should not be able to put xyz. Maybe there is an API yo ucan use to validate cities or another way?

2023-09-08 11:57 UTC, merged