Yacht details page
akos29/book_appointment_front pull request #6
Opened 2023-08-28 21:29 UTC by akos29

Yacht details page 
--
In  this request majorly:

- [x] Add feature to show a details page when the user selects a specific item, they can see the [details page](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579) with its full description
- [x] Add feature to enable user to click the "Reserve" button to book a yacht.

2023-08-29 03:37 UTC, mahabubx7 requested changes
## 🛑 STATUS: REQUIRED CHANGES 🛑 

![gif](https://media.tenor.com/NtsJEyZMuQIAAAAC/not-ok.gif)

Please recover the `tailwindcss` packages & setup. Follow up the settings from `display` branch #5 

- [ ] Also make sure the API (backend) is providing the details instead of static data.
- [ ] Tailwindcss should work properly

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-08-29 03:54 UTC, mahabubx7 commented on .gitignore
> +dist
**[OPTIONAL]**
It's really good that you added `dist` in the ignore, but we are using `CRA` or create-react-app. So, we also need to add `build` folder in here.

2023-08-29 03:56 UTC, mahabubx7 commented on src/App.js
> +/* eslint-disable import/extensions */
You should not use `eslint-disable` at all. Try to fix or reach out your team-members to solve the issues.

2023-08-29 03:57 UTC, mahabubx7 commented on src/components/Display.jsx
> +          <h1>Display yachts!</h1>
**[OPTIONAL]**
The word `yatch` is incorrect. We all fixed that to `yacht`. You can do it too.

2023-08-29 04:00 UTC, mahabubx7 commented on src/components/yacht/YachtDetail.jsx
> +  };
Please try to resolve or make the API call (backend-repo) first and then implement in frontend app. So, that we can use redux store and actual data from API without using fake or static data.

2023-08-29 04:01 UTC, mahabubx7 commented on src/index.css
> -@tailwind utilities;
Please, recover this `tailwindcss` set-up. it is necessary for those who used it in this project.

2023-08-31 10:12 UTC, lugard1 approved these changes
# STATUS: APPROVED 🟢
## Hi @akos29  , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Well done installing the missing packages. ✔
- It's good you resolved the typo issue as requested by the previous reviewer.✔
- The requirements have been met with success. 🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 10:46 UTC, lugard1 approved these changes
# STATUS: APPROVED 🟢
## Hi @akos29  , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- Fix merge issues. ✔
- You documented your work professionally. ✔
- The requirements have been met with success. 🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 22:06 UTC, merged